# ./docker/backend/docker-compose-production.yml

services:
  # back-end
  fastapi_server:
    build:
      context: /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/docker/backend
      dockerfile: Dockerfile
      args:
        # put huggingface token in .env file or .bachrc
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    container_name: fastapi_server
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - IS_FASTAPI_DUMMY=True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/models:/app/models:ro

  # front-end web service
  gradio:
    build:
      context: /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/docker/web
      dockerfile: Dockerfile
    container_name: gradio
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
      - GRADIO_PORT=7860
    ports:
      - "7860:7860"
      
  # System Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/configs/prometheus.yml:/etc/prometheus/prometheus.yml

  # Performance Metrics
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/configs/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/configs/dashboards:/var/lib/grafana/dashboards:ro
      - /home/cc/Fine-Tuning-Taiwanese-Hokkien-LLM-for-Medical-Advising/configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=your-access-key
      - MINIO_ROOT_PASSWORD=your-secret-key
    volumes:
      - minio_data:/data
    command: server /data --console-address ':9001'
    networks:
      - production_net

  minio-init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 your-access-key your-secret-key &&
      mc mb -p myminio/production || echo 'Bucket already exists'
      "
    networks:
      - production_net

networks:
  production_net:
    external: true

volumes:
  minio_data: