# docker-compose.yml
version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # put huggingface token in .env file or .bachrc
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web    
    environment:
      - FASTAPI_SERVER_URL=http://fastapi:8000
    ports:
      - "7860:7860"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    #volumes:
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  models-cache: